FROM node:20.4.0

WORKDIR /app

ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV SWAGGER_API_DOC_PATH=$SWAGGER_API_DOC_PATH

RUN git clone https://github.com/IDPA-2024/Nr.2_TravelerGuide.git .

RUN npm install

RUN npm run build

ENTRYPOINT [ "npm", "run", "start" ]