name: "Build and Push to GHCR"
on:
  push:
    branches:
      - main

env:
  working-directroy: ./

jobs:
  GHCR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          server: ${{ secrets.SSH_SERVER }}
          local_path: "./"
          remote_path: "/nginx/html/lunch"
          sftpArgs: "-o ConnectTimeout=5"
