name: "Build and Push to GHCR"
on:
  push:
    branches:
      - main

env:
  working-directroy: ./

jobs:
  GHCR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd nginx/html/lunch/ |
            sudo docker compose down |
            git pull origin main |
            npm install |
            npm run build |
            sudo docker compose up -d
